name: Deploy ALMA to GitHub Pages

# Activadores del workflow
on:
  # Despliegue automático cuando se hace push a main
  push:
    branches: [ main ]
  
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Ejecutar con logs de debug'
        required: false
        default: 'false'

# Permisos necesarios para el despliegue
permissions:
  contents: write
  pages: write
  id-token: write

# Evita ejecuciones concurrentes
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job único simplificado para build y deploy
  build-and-deploy:
    name: Build y Deploy ALMA Web
    runs-on: ubuntu-latest
    
    steps:
      # ============================================
      # PASO 1: Checkout del código
      # ============================================
      - name: 📥 Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener todo el historial
      
      # ============================================
      # PASO 2: Configurar Flutter
      # ============================================
      - name: 🎯 Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      
      # ============================================
      # PASO 3: Información del entorno (debug)
      # ============================================
      - name: 📋 Información del entorno
        if: github.event.inputs.debug_enabled == 'true'
        run: |
          echo "=== Información del Sistema ==="
          flutter --version
          flutter doctor -v
          echo ""
          echo "=== Información del Repositorio ==="
          echo "Repositorio: ${{ github.repository }}"
          echo "Rama: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
      
      # ============================================
      # PASO 4: Cache de dependencias Pub
      # ============================================
      - name: 📦 Cache de dependencias
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            .dart_tool
            build
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      
      # ============================================
      # PASO 5: Ajuste temporal de dependencias
      # ============================================
      - name: 🔧 Ajustar compatibilidad de dependencias
        run: |
          # Fix temporal para flutter_lints si es necesario
          if grep -q "flutter_lints: \^5\." pubspec.yaml; then
            echo "Ajustando versión de flutter_lints para compatibilidad..."
            sed -i 's/flutter_lints: \^5\.0\.0/flutter_lints: \^4\.0\.0/' pubspec.yaml
          fi
      
      # ============================================
      # PASO 6: Instalar dependencias
      # ============================================
      - name: 📥 Instalar dependencias
        run: |
          flutter config --enable-web
          flutter pub get
      
      # ============================================
      # PASO 7: Análisis de código (no bloqueante)
      # ============================================
      - name: 🔍 Análisis de código
        run: flutter analyze || echo "⚠️ Advertencias en análisis (continuando...)"
        continue-on-error: true
      
      # ============================================
      # PASO 8: Ejecutar tests (no bloqueante)
      # ============================================
      - name: 🧪 Ejecutar tests
        run: |
          flutter test --coverage || echo "⚠️ Algunos tests fallaron (continuando...)"
        continue-on-error: true
      
      # ============================================
      # PASO 9: Build de producción
      # ============================================
      - name: 🏗️ Build Flutter Web
        run: |
          # Build con optimizaciones para producción
          flutter build web \
            --release \
            --base-href /alma/ \
            --web-renderer canvaskit \
            --dart-define=ENVIRONMENT=production \
            --dart-define=BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
            --dart-define=BUILD_NUMBER=${{ github.run_number }}
          
          # Asegurar archivos necesarios para GitHub Pages
          touch build/web/.nojekyll
          
          # Crear 404.html para manejo de rutas
          cat > build/web/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="UTF-8">
            <title>ALMA - Aprendizaje y Lógica para Mentes Activas</title>
            <script>
              const pathSegments = window.location.pathname.split('/').filter(Boolean);
              const repoName = pathSegments[0];
              if (pathSegments.length > 1) {
                window.location.href = '/' + repoName + '/';
              }
            </script>
          </head>
          <body>
            <p>Redirigiendo a ALMA...</p>
          </body>
          </html>
          EOF
          
          # Crear archivo de información del build
          cat > build/web/build-info.json << EOF
          {
            "version": "1.0.0",
            "buildNumber": "${{ github.run_number }}",
            "buildDate": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}",
            "environment": "production"
          }
          EOF
      
      # ============================================
      # PASO 10: Optimizaciones adicionales
      # ============================================
      - name: ⚡ Optimizaciones de rendimiento
        run: |
          # Comprimir assets si es posible (opcional)
          if command -v gzip >/dev/null 2>&1; then
            find build/web -type f \( -name "*.js" -o -name "*.css" -o -name "*.html" \) \
              -exec gzip -9 -k {} \; 2>/dev/null || true
          fi
          
          # Mostrar tamaño del build
          echo "=== Tamaño del Build ==="
          du -sh build/web/
          echo ""
          echo "=== Archivos principales ==="
          ls -lh build/web/*.js 2>/dev/null || true
          ls -lh build/web/*.html
      
      # ============================================
      # PASO 11: Desplegar a GitHub Pages
      # ============================================
      - name: 🚀 Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: |
            Deploy ALMA Web App v1.0.0
            
            Build: #${{ github.run_number }}
            Commit: ${{ github.sha }}
            Date: ${{ github.event.head_commit.timestamp }}
          cname: ''  # Dejar vacío si no tienes dominio personalizado
      
      # ============================================
      # PASO 12: Notificación de éxito
      # ============================================
      - name: ✅ Despliegue completado
        run: |
          echo "=========================================="
          echo "   DESPLIEGUE COMPLETADO EXITOSAMENTE"
          echo "=========================================="
          echo ""
          echo "🎯 Build Number: #${{ github.run_number }}"
          echo "📦 Commit: ${{ github.sha }}"
          echo "👤 Desplegado por: ${{ github.actor }}"
          echo ""
          echo "🌐 La aplicación estará disponible en:"
          echo "   https://${{ github.repository_owner }}.github.io/alma/"
          echo ""
          echo "⏱️ El sitio puede tardar 2-5 minutos en actualizarse"
          echo ""
          echo "📊 Ver estado del despliegue:"
          echo "   https://github.com/${{ github.repository }}/deployments"
          echo "=========================================="
      
      # ============================================
      # PASO 13: Crear release (opcional, solo tags)
      # ============================================
      - name: 📦 Crear Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/web/build-info.json
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Metadata del workflow
# Última actualización: 2025-08-09
# Versión: 1.0.0
# Proyecto: ALMA - Aprendizaje y Lógica para Mentes Activas